### ISSUE TITLE
Failed initializing nvml!

### ISSUE THREAD

**Issue by mrjncsk** [scorpion-26/gBar#39]
hi,
nice project with potential to become a thing!

i try to run it on hyprland on endeavouros, installed it from aur, 
copied default config and css to .config/gBar
Result:
```bash
gBar bar 0
Set value for ...
...
Failed initializing nvml!
[Exiting due to assert failed]
```

**Comment by scorpion-26** [comment]
This looks like an odd issue with the nvidia drivers to me (I'm assuming you're on nvidia).
gBar finds the nvml so (libnvidia-ml.so), but fails when initializing the library.
A few things, that should help me in finding the exact problem:
 - I've pushed a new commit (b246e9f) with improved error logging. Can you post the error message with this commit?
 - Does running ```nvidia-smi``` result in any errors? (Since it uses the same API as gBar)
 - Did you run gBar multiple times before the issue occured?
 - What version is your nvidia driver?
 - Do you have a second GPU (e.g. integrated graphics(Optimus/PRIME), second graphics card, ...)

**Comment by mrjncsk** [comment]
thank you verry much for your response

new message is: 
Failed initializing nvml (Error: 9)!

nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

no, i didnt run it multiple times

Nvidia is the newest driver 535.98-4

i use a external GPU, Nvidia 3060 just for ai computing
currently turned off

i installed many nvidia stuff for ai to work
maybe here is the problem

**Comment by scorpion-26** [comment]
> nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

Can you run ```lsmod | grep nvidia``` and see if there is any output, meaning the nvidia driver is loaded?
If there isn't any output, then that is probably the problem.
Since you seem to have a nvidia GPU only for compute, I'm unsure whether you can just manually load the nvidia module via ```modprobe nvidia```. It could be worth a try.

> i use a external GPU, Nvidia 3060 just for ai computing

If I understand correctly, you have two GPUs (Correct me if I misunderstood something):
- A Nvidia one for AI computing, which isn't connected to a display.
- Another one, which is for display.

Is that other GPU also a NVIDIA GPU or from another vendor?
If it isn't, it makes probably the most sense to just disable the nvidia GPU status if ```nvmlInit``` fails.
If the display GPU is an AMD one, then it would fall back to the AMD GPU status anyways.

**Comment by mrjncsk** [comment]
lsmod | grep nvidia
no output

sudo modprobe nvidia
modprobe: ERROR: could not insert 'nvidia': No such device

yes, 1st GPU is intel tigerlake (intel nuc 11)

**Comment by scorpion-26** [comment]
Okay, gBar should no longer crash (The Nvidia module is disabled on failure).
Unfortunately, Intel GPUs have no good API for querying usage iirc, so gBar can't use the Intel one for the GPU module.

I'm closing this, since the issue with gBar is now fixed. Feel free to contact me, if there are any further issues with gBar.

**Comment by mrjncsk** [comment]
excellent, thank you
