### ISSUE TITLE
Cannot find config

### ISSUE THREAD

**Issue by ItsBoppy** [scorpion-26/gBar#46]
It seems to look for a config and fails into oblivion.
The exact error is:

Failed opening config!
Wayland: Registering monitor DP-2 at ID 0
Wayland: Registering monitor DP-3 at ID 1
NVML not found, disabling Nvidia GPU
AMD GPU not found, disabling AMD GPU
PulseAudio: Context is ready!
PulseAudio: Update info
Cannot open network device! Disabling Network widget.
Info: No CSS found in /home/user/.config
Info: No CSS found in /home/user/.local/share
CSS found and loaded successfully!
Cannot find plugin library!
[Exiting due to assert failed]

apologies if  I'm dumb but I can't seem to find the solution.
I really like this bar its by far one of the better wayland bars out there.

**Comment by scorpion-26** [comment]
```Failed to opening config``` is not the critical error here. gBar fails, because you specified an invalid widget to open. ```gBar bar 0``` should typically work (Commands for the other builtin widgets can be found under [Running gBar](https://github.com/scorpion-26/gBar#configuration-for-your-system)).

If you want to configure gBar, you can follow the steps in [Configuration for your System](https://github.com/scorpion-26/gBar#configuration-for-your-system) for config and [FAQ/I want to customize the colors](https://github.com/scorpion-26/gBar#configuration-for-your-system) for changing the css used.
